# Generated by Django 5.0.6 on 2024-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("study", "重要学习"),
                    ("work", "重要工作"),
                    ("exercise", "锻炼"),
                    ("life", "日常生活"),
                    ("rest", "休息"),
                    ("entertainment", "娱乐"),
                ],
                default="rest",
                max_length=20,
            ),
        ),
    ]
